// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
public class Authentication {
    public int Authenticator_Id;
    public String Authenticator_Name;
    public String Authenticator_Password;

    public Authentication(int authenticator_Id, String authenticator_Name, String authenticator_Password) {
        this.Authenticator_Id = authenticator_Id;
        this.Authenticator_Name = authenticator_Name;
        this.Authenticator_Password = authenticator_Password;
    }

    public void manageTraffic() {
        System.out.println("Traffic management initiated by " + Authenticator_Name);
    }

    // Method to authenticate traffic operator
    public boolean isAuthenticated(int authenticator_Id, String authenticator_Password) {
        return this.Authenticator_Id == authenticator_Id && this.Authenticator_Password.equals(authenticator_Password);
    }
}
