// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
class DisabledPedestrians {
	/**
	 * 
	 */
	public String DisabledPedestrianLocation;
	/**
	 * 
	 */
	public boolean AssistanceRequired;

	/**
	 * 
	 * @param AssistanceRequired 
	 */
	public void isAssistanceReq(EBoolean AssistanceRequired) {
	}

	/**
	 * 
	 * @return 
	 */
	public EString isButtonPressed() {
	}
}
