// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
public class EmergencyResponder extends Emergency {
    private String responderType;

    public EmergencyResponder(int id, String type, String responderType) {
        super(id, type);
        this.responderType = responderType;
    }

    public String getResponderType() {
        return responderType;
    }

    public void setResponderType(String responderType) {
        this.responderType = responderType;
    }
    
    public void handleEmergency(IRoute assignedRoute) {
        System.out.println("Handling emergency: " + getType());
        System.out.println("Occupying route: " + assignedRoute.getRouteName());
    }
}

