// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
public class Maintenance {
	/**
	 * 
	 */
	public EEList scheduled;
	/**
	 * 
	 */
	public EEList unscheduled;
	/**
	 * 
	 */
	public int Maintenance_Type;
	/**
	 * 
	 */
	public int Maintenance_Id;
	/**
	 * 
	 */
	public int Maintenance_Date;

	/**
	 * 
	 * @param Sensor_Id 
	 * @param MantenanceType 
	 * @param Maintenance_date 
	 */
	public void performMaintenance(int Sensor_Id, int MantenanceType, EDate Maintenance_date) {
	}

	/**
	 * 
	 */
	public void getScheduledList() {
	}

	/**
	 * 
	 */
	public void getUnscheduled() {
	}
}
