// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
public class Notification {
	/**
	 * 
	 */
	public int NotificationId;
	/**
	 * 
	 */
	public EString NotificationDescription;

	/**
	 * 
	 * @param NotificationId 
	 * @return 
	 */
	public EString DisplayNotification(int NotificationId) {
	}
}
