// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
public class Parking system
{
	/**
	 * 
	 */
	public int ParkingId;
	/**
	 * 
	 */
	public EEList NearestParking;

	/**
	 * 
	 * @param ParkingId 
	 */
	public void getNearestParkingById(int ParkingId) {
	}
}
