// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
class Pedestrian extends TrafficSignal {
	/**
	 * 
	 */
	public int PedestrianLocation;

	/**
	 * 
	 * @return 
	 */
	public String isButtonPressed() {
	}
}
