// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
class Sensor {
	/**
	 * 
	 */
	public int Sensor_Type;
	/**
	 * 
	 */
	public int Sensor_Id;
	/**
	 * 
	 */
	public String Sensor_Location;
	/**
	 * 
	 */
	int Route_Id;

	/**
	 * 
	 * @param Sensor_Id 
	 * @return 
	 */
	public String activateSensor(int Sensor_Id) {
	}

	/**
	 * 
	 * @param Sensor_id 
	 */
	public void disableSensor(undef Sensor_id) {
	}
}
