// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
public class Signal Coordination
{

	/**
	 * 
	 */
	public void monitorTiming() {
	}

	/**
	 * 
	 */
	public void syncControl() {
	}
}
