// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
class TrafficSignal {
	/**
	 * 
	 */
	public int signalID;
	/**
	 * 
	 */
	protected int LocationId;
	/**
	 * 
	 */
	public int state;
	/**
	 * 
	 */
	public Sensor[] sensor;

	/**
	 * 
	 * @param signalID 
	 * @return 
	 */
	public String changeSignalState(int signalID) {
	}

	/**
	 * 
	 */
	public void timerState() {
	}

	/**
	 * 
	 */
	public void stoptimer() {
	}

	/**
	 * 
	 */
	public void startTimer() {
	}

	/**
	 * 
	 * @return 
	 */
	String isButtonPressed() {
	}
}
