// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
public class Vehicle {
	/**
	 * 
	 */
	public int Driver_License_Id;
	/**
	 * 
	 */
	public int vehicleID;
	/**
	 * 
	 */
	public int VehicleType;
	/**
	 * 
	 */
	public String[] Driver_Name;
	/**
	 * 
	 */
	public String Driver_Address;
	/**
	 * 
	 */
	public String EmergencyContact;
	/**
	 * 
	 */
	public undef License_Class;
	/**
	 * 
	 */
	public int ContactInfo;
	/**
	 * 
	 */
	public String DrivingHistory;

	/**
	 * 
	 * @param Driver_License_Id 
	 */
	public void RecordIncident(int Driver_License_Id) {
	}

	/**
	 * 
	 * @param Driver_License_Id 
	 */
	public void getDrivingHistory(int Driver_License_Id) {
	}
}
