// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
public class VIP extends Emergency {
    private String vipType;
    public VIP(int id, String type, String vipType) {
        super(id, type);
        this.vipType = vipType;
    }

    public String getVipType() {
        return vipType;
    }

    public void setVipType(String vipType) {
        this.vipType = vipType;
    }
    
    @Override
    public void handleEmergency(int id, String type) {
        // Custom handling code for VIP emergencies
        System.out.println("Handling VIP emergency...");
        super.handleEmergency(id, type); // Call to the superclass method
    }
}