// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
public class WeatherAlert extends Emergency {
    private String alertType;

    public WeatherAlert(int id, String type, String alertType) {
        super(id, type);
        this.alertType = alertType;
    }

    public String getAlertType() {
        return alertType;
    }

    public void setAlertType(String alertType) {
        this.alertType = alertType;
    }
}