// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
public class Weather report
{
	/**
	 * 
	 */
	public int RainForecast;
	/**
	 * 
	 */
	public EDate Date;
}
