// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package TrafficControl;

/************************************************************/
/**
 * 
 */
public class Yellow extends TrafficSignal {
	/**
	 * 
	 */
	public int Duration;

	/**
	 * 
	 */
	public void startTimer() {
	}

	/**
	 * 
	 */
	public void stopTimer() {
	}
}
